// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaGerencial.Infrastructure.Persistence;

#nullable disable

namespace SistemaGerencial.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.CuentaPorCobrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<long>("MontoCobradoCentimos")
                        .HasColumnType("bigint");

                    b.Property<long>("MontoTotalCentimos")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<bool>("TieneIgv")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<long>("MontoPagadoCentimos")
                        .HasColumnType("bigint");

                    b.Property<long>("MontoTotalCentimos")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<bool>("TieneIgv")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<string>("Configuracion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaActiva")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rubro")
                        .HasColumnType("text");

                    b.Property<string>("Ruc")
                        .HasColumnType("text");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreadoPor")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CuentaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaConciliado")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("FechaMovimiento")
                        .HasColumnType("date");

                    b.Property<Guid?>("GastosRecurrentesId")
                        .HasColumnType("uuid");

                    b.Property<long>("IgvCentimos")
                        .HasColumnType("bigint");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MontoCentimos")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<bool>("TieneIgv")
                        .HasColumnType("boolean");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("MovimientosCaja");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.SesionActiva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("text");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SesionesActivas");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstaDeAcuerdoPolitica")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaAcuerdoPolitica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiereCambioPassword")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TfaHabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("TfaSecret")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.CuentaPorCobrar", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.CuentaPorPagar", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Rol", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Roles")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.SesionActiva", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaGerencial.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGerencial.Domain.Entities.Rol", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaGerencial.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
